# Generated by Django 5.2.3 on 2025-08-27 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("model_path", models.CharField(max_length=500)),
                ("labels_path", models.CharField(max_length=500)),
                ("confidence_threshold", models.FloatField(default=0.5)),
                ("nms_threshold", models.FloatField(default=0.4)),
                ("max_detections", models.IntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "model_configurations",
            },
        ),
        migrations.CreateModel(
            name="VideoSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("CAMERA", "Live Camera"),
                            ("FILE", "Video File"),
                            ("STREAM", "Video Stream"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_url", models.CharField(blank=True, max_length=500, null=True)),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "video_sources",
            },
        ),
        migrations.CreateModel(
            name="DetectionSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("COMPLETED", "Completed"),
                            ("ERROR", "Error"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("total_frames_processed", models.IntegerField(default=0)),
                ("total_detections", models.IntegerField(default=0)),
                ("processing_notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "detection_sessions",
            },
        ),
        migrations.CreateModel(
            name="ROI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("x_coordinate", models.IntegerField()),
                ("y_coordinate", models.IntegerField()),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "video_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="object_detection.videosource",
                    ),
                ),
            ],
            options={
                "db_table": "rois",
            },
        ),
        migrations.CreateModel(
            name="DetectionResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("frame_number", models.IntegerField()),
                ("timestamp", models.DateTimeField()),
                ("detected_objects", models.JSONField()),
                ("confidence_scores", models.JSONField()),
                ("bounding_boxes", models.JSONField()),
                ("processing_time", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="object_detection.detectionsession",
                    ),
                ),
                (
                    "video_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="object_detection.videosource",
                    ),
                ),
            ],
            options={
                "db_table": "detection_results",
            },
        ),
    ]
